// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://puusxbrrttldbileibqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB1dXN4YnJydHRsZGJpbGVpYnF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyOTAxNDMsImV4cCI6MjA2Mjg2NjE0M30.I6zVykiA2Zo81vurqmDp7NKiHdMlqTy2Q3jcDMKSNSc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);